name: Terraform Destroy AWS

on:
  workflow_dispatch:   # 👈 Manual trigger

env:
  AWS_REGION: ap-south-1
  TF_VERSION: 1.6.6

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Select environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "env_path=envs/prod" >> $GITHUB_ENV
          else
            echo "env_path=envs/dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.env_path }} init -reconfigure

      - name: Terraform Validate
        run: terraform -chdir=${{ env.env_path }} validate

      - name: Terraform Destroy
        run: terraform -chdir=${{ env.env_path }} destroy -auto-approve
